//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public string Debilidad { get; set; }
        public string Evolucion { get; set; }
        public Nullable<decimal> Peso { get; set; }
        public int Numero { get; set; }
    }
}
